{% set name = "torchdata" %}
{% set version = "0.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/pytorch/data/archive/refs/tags/v{{ version }}.tar.gz
  sha256: b4ec446a701680faa620fcb828b98ba36a63fa79da62a1e568d4a683889172da

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - requests
    - urllib3 >=1.25
    - portalocker >=2.0.0
    - pytorch >=1.12.0
    # https://github.com/pytorch/data#version-compatibility
    - python >=3.7

test:
  imports:
    - torchdata
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/pytorch/data
  summary: A PyTorch repo for data loading and utilities to be shared by the PyTorch domain libraries.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - BastianZim
